<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Mo\**" />
    <EmbeddedResource Remove="Mo\**" />
    <None Remove="Mo\**" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Models\DTOs\" />
  </ItemGroup>

</Project>
